---
# - debug:
#     msg: "{{ instruction_index }}"

- name: Move the boxes
  ansible.utils.update_fact:
    updates:
      - path: "stacks[{{ move_to | int }}]"
        value:
          "{% if reverse %}{{ stack_from | default([]) | json_query(to_query) | reverse + stack_to | default([])}}{% else %}{{ stack_from | default([]) | json_query(to_query) + stack_to | default([])}}{% endif %}"
      - path: "stacks[{{ move_from | int }}]"
        value: "{{ stack_from | default([]) | json_query(from_query) }}"
  vars:
    stack_from: "{{ stacks[move_from | int ] }}"
    stack_to: "{{ stacks[move_to | int ] }}"
    from_query: "[{{ amount | int }}:]"
    to_query: "[:{{ amount | int }}]"
  register: stacks

- name: Set stacks to the last result
  ansible.builtin.set_fact:
    stacks: "{{ stacks.stacks }}"
